[doctor]
checks = [
  {check = "homebrew"},
  {check = "tool-versions", command = "plugin-installed", args = {plugin = "rust"}},
  {check = "tool-versions", command = "package-installed", args = {plugin = "rust"}},
  {check = "rust", command = "crate-installed", args = {name = ["cargo-audit","cargo-outdated"]}},
  {check = "rust", command = "target-installed", args = {target = ["aarch64-apple-darwin", "x86_64-apple-darwin"]}},
]

[test]
checks = [
  {step = "rust", command = "test", verbose = true},
  {name = "Check for warnings", shell = "cargo build --features strict --color always"},
]

[audit]
checks = [
  {check = "rust", command = "audit", verbose = true},
  {name = "rust: check", shell = "cargo check", remedy = "cargo fix --allow-dirty"},
  {name = "rust: clippy", shell = "cargo clippy -- -D warnings", remedy = "cargo clippy --fix --allow-dirty"},
  {check = "rust", command = "format-check"},
]

[outdated]
checks = [
  {check = "rust"},
]

[update]
steps = [
  {step = "git", command = "pull"},
  {doctor = {}},
]

[shipit]
steps = [
  {audit = {}},
  {update = {}},
  {test = {}},
  {step = "git", command = "push"},
]

